spring:
  rabbitmq:
    host: 10.184.15.218
    port: 15672
    username: admin
    password: Abcd12345
    virtual-host:
    listener:
      simple:
        acknowledge-mode: manual
    ssl:
      enabled: false

server:
  port: 5006
  servlet:
    context-path: /WeBASE-Event-Client

constant:
  frontIpPort: 10.184.15.218:5002

logging:
  config: classpath:log4j2.xml
